let products = [
  {
    id: "111",
    namCar: "2023 Nissan Versa S FWD",
    priceCar: "18,377",
    imgCar: [
      "../images/car1/0.png",
      "../images/car1/1 (1).jpeg",
      "../images/car1/1 (1).jpg",
      "../images/car1/1 (2).jpg",
      "../images/car1/1 (3).jpg",
      "../images/car1/1 (4).jpg",
      "../images/car1/1 (4).jpg",
      "../images/car1/1 (5).jpg",
    ],
    features: [
      "Mileage, 2,000",
      "Ext. Color,Silver",
      "MPG,MPG36",
      "Fuel type,Gasoline",
      "Drivetrain,Front-Wheel Drive",
      "int. Color,Gra",
      "Engine,122 hp 1.6L I4",
      "Transmission, Continuously Variable Transmission",
    ],
  },
  {
    id: "112",
    namCar: "2022 Toyota RAV4 LE AWD",
    priceCar: "27,308",
    imgCar: [
      "../images/car2/1 (1).jpeg",
      "../images/car2/1 (2).jpeg",
      "../images/car2/1 (3).jpeg",
      "../images/car2/1 (4).jpeg",
      "../images/car2/1 (5).jpeg",
      "../images/car2/1 (6).jpeg",
      "../images/car2/1 (7).jpeg",
      "../images/car2/1 (8).jpeg",
      "../images/car2/1 (9).jpeg",
      "../images/car2/1 (10).jpeg",
    ],
    features: [
      "Mileage, 24,024",
      "Ext. Color,white",
      "MPG, 30MPG",
      "Fuel type, Gasoline",
      "Drivetrain,All-Wheel Drive",
      "int. Color, Nutmeg",
      "Engine,2.5L I4",
      "Transmission, 8-Speed Automatic",
    ],
  },
  {
    id: "113",
    namCar: "2022 Honda Accord Sport FWD",
    priceCar: "25,508",
    imgCar: [
      "../images/car3/1 (1).jpeg",
      "../images/car3/1 (2).jpeg",
      "../images/car3/1 (3).jpeg",
      "../images/car3/1 (4).jpeg",
      "../images/car3/1 (5).jpeg",
      "../images/car3/1 (6).jpeg",
      "../images/car3/1 (7).jpeg",
      "../images/car3/1 (8).jpeg",
      "../images/car3/1 (9).jpeg",
    ],
    features: [
      "Mileage, 35,503",
      "Ext. Color,San Marino Red",
      "MPG, 32 MPG",
      "Fuel type, Gasoline",
      "Drivetrain,Front-Wheel Drive",
      "int. Color, Black",
      "Engine,192 hp 1.5L I4",
      "Transmission, Continuously Variable Transmission",
    ],
  },
  {
    id: "114",
    namCar: "2021 Toyota RAV4 XLE FWD",
    priceCar: "22,258",
    imgCar: [
      "../images/car4/1 (1).jpeg",
      "../images/car4/1 (2).jpeg",
      "../images/car4/1 (3).jpeg",
      "../images/car4/1 (4).jpeg",
      "../images/car4/1 (5).jpeg",
      "../images/car4/1 (6).jpeg",
      "../images/car4/1 (7).jpeg",
    ],
    features: [
      "Mileage, 61,462",
      "Ext. Color,black",
      "MPG, 31 MPG",
      "Fuel type, Gasoline",
      "Drivetrain,Front-Wheel Drive",
      "int. Color, Black",
      "Engine,2.5L I4",
      "Transmission, 8-Speed Automatic",
    ],
  },
  {
    id: "115",
    namCar: "2021 Toyota RAV4 XLE FWD",
    priceCar: "22,258",
    imgCar: [
      "../images/car5/1 (1).jpg",
      "../images/car5/1 (2).jpeg",
      "../images/car5/1 (3).jpeg",
      "../images/car5/1 (4).jpeg",
      "../images/car5/1 (5).jpeg",
      "../images/car5/1 (6).jpeg",
      "../images/car5/1 (7).jpeg",
      "../images/car5/1 (8).jpeg",
      "../images/car5/1 (9).jpeg",
      "../images/car5/1 (10).jpeg",
    ],
    features: [
      "Mileage, 61,462",
      "Ext. Color,black",
      "MPG, 31 MPG",
      "Fuel type, Gasoline",
      "Drivetrain,Front-Wheel Drive",
      "int. Color, Black",
      "Engine,2.5L I4",
      "Transmission, 8-Speed Automatic",
    ],
  },
  {
    id: "116",
    namCar: "2021 Toyota RAV4 XLE FWD",
    priceCar: "22,258",
    imgCar: [
      "../images/car6/1 (1).png",
      "../images/car6/1 (2).png",
      "../images/car6/1 (3).png",
      "../images/car6/1 (4).png",
      "../images/car6/1 (5).png",
      "../images/car6/1 (6).png",
      "../images/car6/1 (7).png",
      "../images/car6/1 (8).png",
      "../images/car6/1 (9).png",
      "../images/car6/1 (10).png",
    ],
    features: [
      "Mileage, 61,462",
      "Ext. Color,black",
      "MPG, 31 MPG",
      "Fuel type, Gasoline",
      "Drivetrain,Front-Wheel Drive",
      "int. Color, Black",
      "Engine,2.5L I4",
      "Transmission, 8-Speed Automatic",
    ],
  },
  {
    id: "117",
    namCar: "2020 Lexus NX Hybrid 300h AWD",
    priceCar: "28,258",
    imgCar: [
      "../images/car7/1 (1).avif",
      "../images/car7/1 (1).jpg",
      "../images/car7/1 (2).avif",
      "../images/car7/1 (2).jpg",
      "../images/car7/1 (3).avif",
      "../images/car7/1 (4).jpg",
    ],
    features: [
      "Mileage, 61,462",
      "Ext. Color,Atomic Silver",
      "MPG, 32 MPG",
      "Fuel type, Hybrid",
      "Drivetrain,All-Wheel Drive",
      "int. Color,194 hp 2.5L I4 Hybrid",
      "Engine,2.5L I4",
      "Transmission,Continuously Variable Transmission",
    ],
  },
  {
    id: "118",
    namCar: "2023 Jeep Compass",
    priceCar: "29,776",
    imgCar: [
      "../images/car8/img-1-600x400.avif",
      "../images/car8/img-2-600x400.avif",
      "../images/car8/img-3-600x400.avif",
      "../images/car8/img-5-600x400.avif",
      "../images/car8/img-6-600x400.avif",
      "../images/car8/img-7-600x400.jpg",
    ],
    features: [
      "Mileage, 61,462",
      "Ext. Color,Atomic Silver",
      "MPG, 32 MPG",
      "Fuel type, Hybrid",
      "Drivetrain,All-Wheel Drive",
      "int. Color,194 hp 2.5L I4 Hybrid",
      "Engine,2.5L I4",
      "Transmission,Continuously Variable Transmission",
    ],
  },
  {
    id: "119",
    namCar: "2024 Jeep Wrangler",
    priceCar: "44,603",
    imgCar: [
      "../images/car9/2024_jeep_wrangler_convertible-suv_sport-s_tds_izmo_10_600x400.avif",
      "../images/car9/2024_jeep_wrangler_convertible-suv_sport-s_tds2_izmo_10_1280.jpg",
      "../images/car9/2024_jeep_wrangler_convertible-suv_sport-s_tds3_izmo_10_1280.jpg",
      "../images/car9/2024_jeep_wrangler_convertible-suv_sport-s_tds_izmo_10_600x400.avif",
    ],
    features: [
      "Mileage, 61,462",
      "Ext. Color,Atomic Silver",
      "MPG, 32 MPG",
      "Fuel type, Hybrid",
      "Drivetrain,All-Wheel Drive",
      "int. Color,194 hp 2.5L I4 Hybrid",
      "Engine,2.5L I4",
      "Transmission,Continuously Variable Transmission",
    ],
  },
  {
    id: "120",
    namCar: "2024 Jeep Compass",
    priceCar: "43,783",
    imgCar: [
      "../images/car10/img-1-960x.jpg",
      "../images/car10/img-2-960x.jpg",
      "../images/car10/img-3-960x.jpg",
      "../images/car10/img-5-960x.jpg",
      "../images/car10/img-6-960x.jpg",
      "../images/car10/img-7-960x.jpg",
      "../images/car10/img-8-960x.jpg",
    ],
    features: [
      "Mileage, 61,462",
      "Ext. Color,Atomic Silver",
      "MPG, 32 MPG",
      "Fuel type, Hybrid",
      "Drivetrain,All-Wheel Drive",
      "int. Color,194 hp 2.5L I4 Hybrid",
      "Engine,2.5L I4",
      "Transmission,Continuously Variable Transmission",
    ],
  },
  {
    id: "121",
    namCar: "2024 Jeep Grand Cherokee L",
    priceCar: "56,103",
    imgCar: [
      "../images/car11/2022_jeep_grand-cherokee-l_4dr-suv_limited_fq_oem_1_1280.avif",
      "../images/car11/2022_jeep_grand-cherokee-l_4dr-suv_limited_rq_oem_1_1280.jpg",
    ],
    features: [
      "Mileage, 61,462",
      "Ext. Color,Atomic Silver",
      "MPG, 32 MPG",
      "Fuel type, Hybrid",
      "Drivetrain,All-Wheel Drive",
      "int. Color,194 hp 2.5L I4 Hybrid",
      "Engine,2.5L I4",
      "Transmission,Continuously Variable Transmission",
    ],
  },
  {
    id: "122",
    namCar: "2024 GMC Sierra 3500HD",
    priceCar: "86,248",
    imgCar: [
      "../images/car12/1 (1).avif",
      "../images/car12/1 (1).jpeg",
      "../images/car12/1 (2).jpeg",
      "../images/car12/1(4).webp",
    ],
    features: [
      "Mileage, 61,462",
      "Ext. Color,Atomic Silver",
      "MPG, 32 MPG",
      "Fuel type, Hybrid",
      "Drivetrain,All-Wheel Drive",
      "int. Color,194 hp 2.5L I4 Hybrid",
      "Engine,2.5L I4",
      "Transmission,Continuously Variable Transmission",
    ],
  },
];
